name: release
on:
  push:
    tags:
      - "v*"
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            target: x86_64-apple-darwin
            out_os: darwin
            out_arch: amd64
            use_cross: false
          - os: macos-14
            target: aarch64-apple-darwin
            out_os: darwin
            out_arch: arm64
            use_cross: false
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            out_os: linux
            out_arch: amd64
            use_cross: false
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
            out_os: linux
            out_arch: arm64
            use_cross: true
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            out_os: windows
            out_arch: amd64
            use_cross: false

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Perl and NASM (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install strawberryperl nasm -y
          echo "C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Set OpenSSL env for Linux
        if: runner.os == 'Linux'
        run: |
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
          echo "OPENSSL_NO_VENDOR=0" >> $GITHUB_ENV

      - name: Cargo build (release)
        run: |
          if [[ "${{ matrix.use_cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
        shell: bash
        env:
          OPENSSL_STATIC: ${{ runner.os == 'Linux' && '1' || '' }}
          OPENSSL_NO_VENDOR: ${{ runner.os == 'Linux' && '0' || '' }}

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail
          BIN=phpvm
          OUTDIR=dist
          mkdir -p "$OUTDIR"
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            SRC="target/${{ matrix.target }}/release/${BIN}.exe"
            ARCHIVE="${OUTDIR}/${BIN}-${{ matrix.out_os }}-${{ matrix.out_arch }}.zip"
            if command -v 7z >/dev/null 2>&1; then
              7z a "$ARCHIVE" "$SRC"
            else
              powershell Compress-Archive -Path "$SRC" -DestinationPath "$ARCHIVE"
            fi
          else
            SRC="target/${{ matrix.target }}/release/${BIN}"
            TARBALL="${OUTDIR}/${BIN}-${{ matrix.out_os }}-${{ matrix.out_arch }}.tar.gz"
            tar -C "$(dirname "$SRC")" -czf "$TARBALL" "$(basename "$SRC")"
          fi

      - name: Generate checksums
        shell: bash
        run: |
          set -euo pipefail
          cd dist
          shopt -s nullglob
          rm -f SHA256SUMS
          for f in *.tar.gz *.zip; do
            [ -f "$f" ] || continue
            if command -v sha256sum >/dev/null 2>&1; then
              sha256sum "$f" >> SHA256SUMS
            else
              shasum -a 256 "$f" >> SHA256SUMS
            fi
          done

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}